x-superset-image: &superset-image
  ghcr.io/securehst/securehst-insights:${TAG:-latest}

x-superset-volumes:
  &superset-volumes
  - ./docker/requirements-local.txt:/app/docker/requirements-local.txt
  - ./assets/logo.png:/app/superset/static/assets/images/logo.png
  - ./assets/favicon.png:/app/superset/static/assets/images/favicon.png
  - superset_home:/app/superset_home

x-superset-defaults: &superset-defaults
  env_file:
    - path: .env
      required: true
  environment:
    DATABASE_DB: superset
    DATABASE_HOST: db
    DATABASE_PORT: "5432"
    DATABASE_DIALECT: postgresql
    DATABASE_USER: superset
    POSTGRES_DB: superset
    POSTGRES_USER: superset
    POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    REDIS_HOST: redis
    REDIS_PORT: "6379"
    PYTHONPATH: /app/pythonpath:/app/docker/pythonpath_dev
    PYTHONUNBUFFERED: "1"
    FLASK_DEBUG: "false"
    SUPERSET_LOG_LEVEL: info
    SUPERSET_LOAD_EXAMPLES: "no"
    COMPOSE_PROJECT_NAME: superset

services:
  db:
    image: postgres:16
    platform: linux/amd64
    container_name: superset_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: superset
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - db_home:/var/lib/postgresql/data

  redis:
    image: redis:7
    platform: linux/amd64
    container_name: superset_cache
    restart: unless-stopped
    volumes:
      - redis:/data

  superset-init:
    image: *superset-image
    platform: linux/amd64
    container_name: superset_init
    command: ["/app/docker/docker-init.sh"]
    <<: *superset-defaults
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
    user: "root"
    volumes: *superset-volumes
    healthcheck:
      disable: true

  superset:
    image: *superset-image
    platform: linux/amd64
    container_name: superset_app
    command: ["/app/docker/docker-bootstrap.sh", "app-gunicorn"]
    <<: *superset-defaults
    restart: unless-stopped
    ports:
      - "${SUPERSET_PORT:-8088}:8088"
    depends_on:
      superset-init:
        condition: service_completed_successfully
    user: "root"
    volumes: *superset-volumes

  superset-worker:
    image: *superset-image
    platform: linux/amd64
    container_name: superset_worker
    command: ["/app/docker/docker-bootstrap.sh", "worker"]
    <<: *superset-defaults
    restart: unless-stopped
    depends_on:
      superset-init:
        condition: service_completed_successfully
    user: "root"
    volumes: *superset-volumes
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "celery -A superset.tasks.celery_app:app inspect ping -d celery@$$HOSTNAME",
        ]

  superset-worker-beat:
    image: *superset-image
    platform: linux/amd64
    container_name: superset_worker_beat
    command: ["/app/docker/docker-bootstrap.sh", "beat"]
    <<: *superset-defaults
    restart: unless-stopped
    depends_on:
      superset-init:
        condition: service_completed_successfully
    user: "root"
    volumes: *superset-volumes
    healthcheck:
      disable: true

volumes:
  superset_home:
    external: false
  db_home:
    external: false
  redis:
    external: false
